// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#include "hfi_common.h"
#include "hfi_io_common.h"
#include <linux/io.h>

#define VIDC_VBIF_BASE_OFFS_AR50			0x00080000

#define VIDC_CPU_BASE_OFFS_AR50			0x000C0000
#define VIDC_CPU_CS_BASE_OFFS_AR50		(VIDC_CPU_BASE_OFFS_AR50 + 0x00012000)
#define VIDC_CPU_IC_BASE_OFFS		(VIDC_CPU_BASE_OFFS_AR50 + 0x0001F000)

#define VIDC_CPU_CS_A2HSOFTINTCLR_AR50	(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x1C)
#define VIDC_CPU_CS_SCIACMD_AR50			(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x48)

/* HFI_CTRL_STATUS */
#define VIDC_CPU_CS_SCIACMDARG0_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x4C)
#define VIDC_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK_AR50	0xfe
#define VIDC_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY_AR50           0x100
#define VIDC_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_IDLE_MSG_BMSK_AR50     0x40000000

/* HFI_QTBL_INFO */
#define VIDC_CPU_CS_SCIACMDARG1_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x50)

/* HFI_QTBL_ADDR */
#define VIDC_CPU_CS_SCIACMDARG2_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x54)

/* HFI_VERSION_INFO */
#define VIDC_CPU_CS_SCIACMDARG3_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x58)

/* VIDC_SFR_ADDR */
#define VIDC_CPU_CS_SCIBCMD_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x5C)

/* VIDC_MMAP_ADDR */
#define VIDC_CPU_CS_SCIBCMDARG0_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x60)

/* VIDC_UC_REGION_ADDR */
#define VIDC_CPU_CS_SCIBARG1_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x64)

/* VIDC_UC_REGION_ADDR */
#define VIDC_CPU_CS_SCIBARG2_AR50		(VIDC_CPU_CS_BASE_OFFS_AR50 + 0x68)

#define VIDC_CPU_IC_SOFTINT_AR50	(VIDC_CPU_IC_BASE_OFFS + 0x18)
#define VIDC_CPU_IC_SOFTINT_H2A_SHFT_AR50	0xF

/*
 * --------------------------------------------------------------------------
 * MODULE: vidc_wrapper
 * --------------------------------------------------------------------------
 */
#define VIDC_WRAPPER_BASE_OFFS_AR50		0x000E0000

#define VIDC_WRAPPER_HW_VERSION_AR50		(VIDC_WRAPPER_BASE_OFFS_AR50 + 0x00)

#define VIDC_WRAPPER_INTR_STATUS_AR50	(VIDC_WRAPPER_BASE_OFFS_AR50 + 0x0C)
#define VIDC_WRAPPER_INTR_STATUS_A2HWD_BMSK_AR50	0x10
#define VIDC_WRAPPER_INTR_STATUS_A2H_BMSK_AR50	0x4

#define VIDC_WRAPPER_INTR_CLEAR_AR50		(VIDC_WRAPPER_BASE_OFFS_AR50 + 0x14)
#define VIDC_WRAPPER_CPU_STATUS_AR50 (VIDC_WRAPPER_BASE_OFFS_AR50 + 0x2014)

#define VIDC_CTRL_INIT_AR50		VIDC_CPU_CS_SCIACMD_AR50

#define VIDC_CTRL_STATUS_AR50	VIDC_CPU_CS_SCIACMDARG0_AR50
#define VIDC_CTRL_ERROR_STATUS__M_AR50 \
		VIDC_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK_AR50
#define VIDC_CTRL_INIT_IDLE_MSG_BMSK_AR50 \
		VIDC_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_IDLE_MSG_BMSK_AR50
#define VIDC_CTRL_STATUS_PC_READY_AR50 \
		VIDC_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY_AR50

#define VIDC_QTBL_INFO_AR50		VIDC_CPU_CS_SCIACMDARG1_AR50

#define VIDC_QTBL_ADDR_AR50		VIDC_CPU_CS_SCIACMDARG2_AR50

#define VIDC_SFR_ADDR_AR50		VIDC_CPU_CS_SCIBCMD_AR50
#define VIDC_MMAP_ADDR_AR50		VIDC_CPU_CS_SCIBCMDARG0_AR50
#define VIDC_UC_REGION_ADDR_AR50	VIDC_CPU_CS_SCIBARG1_AR50
#define VIDC_UC_REGION_SIZE_AR50	VIDC_CPU_CS_SCIBARG2_AR50